from_latest_tag = false
ignore_merge_commits = false
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "zsh-cwd"
owner = "pjvds"
authors = [
  { username = "pjvds", signature = "Pieter Joost van de Sande"}
]
